### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by ReadmeCritic** [watson/awesome-computer-history#18]
https://archive.org/details/Downloaded.2013-The.Napster.Revolution doesn't work, is there an updated link?

**Comment by watson** [comment]
Yeah, I haven't been able to find an updated version. I'm not sure why they took it down :(

**Comment by watson** [comment]
If anyone knows of a working link, please let me know or open an PR :)

**Comment by watson** [comment]
Fixed by #20 (well, only part 1, but I guess it's better than nothing. I doubt we'll see it online in a legal form any time soon anyway)
